### ISSUE TITLE
Main readme

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/research_buddy#11]

**Comment by usmanwardag** [comment]
Which documentation platform should we use? @Urvashi74 
There are some suggestions in the grading rubric? Can you check?

**Comment by usmanwardag** [comment]
Any update? Which doc platform are we using?

**Comment by usmanwardag** [comment]
Let's use jsdoc.

**Comment by Urvashi74** [comment]
jsdoc it is.

**Comment by usmanwardag** [comment]
Sounds good

**Comment by usmanwardag** [comment]
Done.
