### ISSUE TITLE
Get full pdf page text

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/research_buddy#21]
Get the full html of the page person is currently on. If it's a pdf, then extract all the text from it.

**Comment by usmanwardag** [comment]
@sbosenc Did you check? Does this seem feasible?

**Comment by sbosenc** [comment]
@usmanwardag yes, I checked this can be done. I'll commit the code changes.

**Comment by usmanwardag** [comment]
Closing this as we don't need this feature any longer.
