### ISSUE TITLE
Add Coursera and Udemy

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/research_buddy#26]

**Comment by usmanwardag** [comment]
Coursera:
`Coursera:
`https://www.coursera.org/search?query=machine%20learning&`

Udemy:
`Coursera:
`https://www.coursera.org/search?query=machine%20learning&`

Udemy:
Coursera:
`https://www.coursera.org/search?query=machine%20learning&`

Udemy:
`https://www.udemy.com/courses/search/?src=ukw&q=machine+learning`

**Comment by usmanwardag** [comment]
Correct udemy link:

`https://www.udemy.com/courses/search/?src=ukw&q=machine+learning`

**Comment by kriti0207** [comment]
added udemy and coursera links.
