### ISSUE TITLE
Implement front-end functionality

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/research_buddy#3]
Implement design based on #2.

**Comment by usmanwardag** [comment]
Any update on this @muskan7828?

- Does a pop-up appear when the user highlights some thing?
- Can we fetch the query i.e., what the person highlighted?

**Comment by sbosenc** [comment]
1. Function should return/print whatever is selected
2. Detect the pattern of the selected text. Reference if it is starting with [ and ending with ]. Word search if selected text is not more than 4 words
3. Two different popups for word search and abstract search.

**Comment by usmanwardag** [comment]
1 is done. @sbosenc please close the issue once 2 and 3 are done.

**Comment by sbosenc** [comment]
Pop up is now working. Need to work on the styling of the pop-up bubble.

**Comment by usmanwardag** [comment]
Does the content display inside the pop-up? @sbosenc

**Comment by sbosenc** [comment]
@usmanwardag yes the definition is getting displayed inside the popup. Working on integrating the rest of the results in the popup.
